import type { Composition } from '$lib/Noted/types';
import { DrumNote } from '$lib/Noted/NotedDrums';

export const demoComposition: Composition = {
  notes: [
    { value: DrumNote.HIHAT_CLOSED, position: { bar: 0, offset: 0, measure: 8 } },
    { value: DrumNote.HIHAT_CLOSED, position: { bar: 0, offset: 1, measure: 8 } },
    { value: DrumNote.HIHAT_CLOSED, position: { bar: 0, offset: 2, measure: 8 } },
    { value: DrumNote.HIHAT_CLOSED, position: { bar: 0, offset: 3, measure: 8 } },
    { value: DrumNote.HIHAT_CLOSED, position: { bar: 0, offset: 4, measure: 8 } },
    { value: DrumNote.HIHAT_CLOSED, position: { bar: 0, offset: 5, measure: 8 } },
    { value: DrumNote.HIHAT_CLOSED, position: { bar: 0, offset: 6, measure: 8 } },
    { value: DrumNote.HIHAT_CLOSED, position: { bar: 0, offset: 7, measure: 8 } },
    { value: DrumNote.BASSDRUM, position: { bar: 0, offset: 0, measure: 8 } },
    { value: DrumNote.BASSDRUM, position: { bar: 0, offset: 4, measure: 8 } },
    { value: DrumNote.BASSDRUM, position: { bar: 0, offset: 5, measure: 8 } },
    { value: DrumNote.SNARE, position: { bar: 0, offset: 2, measure: 8 } },
    { value: DrumNote.SNARE, position: { bar: 0, offset: 6, measure: 8 } },

    { value: DrumNote.HIHAT_CLOSED, position: { bar: 1, offset: 0, measure: 8 } },
    { value: DrumNote.HIHAT_CLOSED, position: { bar: 1, offset: 1, measure: 8 } },
    { value: DrumNote.HIHAT_CLOSED, position: { bar: 1, offset: 2, measure: 8 } },
    { value: DrumNote.HIHAT_CLOSED, position: { bar: 1, offset: 3, measure: 8 } },
    { value: DrumNote.HIHAT_CLOSED, position: { bar: 1, offset: 4, measure: 8 } },
    { value: DrumNote.HIHAT_CLOSED, position: { bar: 1, offset: 5, measure: 8 } },
    { value: DrumNote.HIHAT_CLOSED, position: { bar: 1, offset: 6, measure: 8 } },
    { value: DrumNote.HIHAT_CLOSED, position: { bar: 1, offset: 7, measure: 8 } },
    { value: DrumNote.BASSDRUM, position: { bar: 1, offset: 0, measure: 8 } },
    { value: DrumNote.BASSDRUM, position: { bar: 1, offset: 4, measure: 8 } },
    { value: DrumNote.BASSDRUM, position: { bar: 1, offset: 5, measure: 8 } },
    { value: DrumNote.SNARE, position: { bar: 1, offset: 2, measure: 8 } },
    { value: DrumNote.SNARE, position: { bar: 1, offset: 6, measure: 8 } },

    { value: DrumNote.HIHAT_CLOSED, position: { bar: 2, offset: 0, measure: 8 } },
    { value: DrumNote.HIHAT_CLOSED, position: { bar: 2, offset: 1, measure: 8 } },
    { value: DrumNote.HIHAT_CLOSED, position: { bar: 2, offset: 2, measure: 8 } },
    { value: DrumNote.HIHAT_CLOSED, position: { bar: 2, offset: 3, measure: 8 } },
    { value: DrumNote.HIHAT_CLOSED, position: { bar: 2, offset: 4, measure: 8 } },
    { value: DrumNote.HIHAT_CLOSED, position: { bar: 2, offset: 5, measure: 8 } },
    { value: DrumNote.HIHAT_CLOSED, position: { bar: 2, offset: 6, measure: 8 } },
    { value: DrumNote.HIHAT_CLOSED, position: { bar: 2, offset: 7, measure: 8 } },
    { value: DrumNote.BASSDRUM, position: { bar: 2, offset: 0, measure: 8 } },
    { value: DrumNote.BASSDRUM, position: { bar: 2, offset: 4, measure: 8 } },
    { value: DrumNote.BASSDRUM, position: { bar: 2, offset: 5, measure: 8 } },
    { value: DrumNote.SNARE, position: { bar: 2, offset: 2, measure: 8 } },
    { value: DrumNote.SNARE, position: { bar: 2, offset: 6, measure: 8 } },

    { value: DrumNote.SNARE, position: { bar: 3, offset: 0, measure: 8 } },
    { value: DrumNote.SNARE, position: { bar: 3, offset: 1, measure: 8 } },
    { value: DrumNote.HIGH_TOM, position: { bar: 3, offset: 2, measure: 8 } },
    { value: DrumNote.HIGH_TOM, position: { bar: 3, offset: 3, measure: 8 } },
    { value: DrumNote.LOW_TOM, position: { bar: 3, offset: 4, measure: 8 } },
    { value: DrumNote.LOW_TOM, position: { bar: 3, offset: 5, measure: 8 } },
    { value: DrumNote.FLOOR_TOM, position: { bar: 3, offset: 6, measure: 8 } },
    { value: DrumNote.FLOOR_TOM, position: { bar: 3, offset: 7, measure: 8 } },
  ],
  meter: [4, 4],
  bpm: 120,
};
